Repository greedy-team/sejong-life-fe, pull requests merged in 2025-08, with the labels that each got.

#4 Chore: MSW 구축
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mock/browser.ts
  src/mock/handler/CategoryEndpoints.ts
  src/mock/handler/PlaceEndpoints.ts
  src/mock/handler/TagEndPoints.ts
  src/mock/handlers.ts
Labels: 🚀 feature, 🔨 chore

#11 chore: TDD 개발을 위한 테스트 툴 세팅
  package-lock.json
  package.json
  src/layout/components/Header.test.tsx
  src/setupTests.ts
  vite.config.ts
Labels: 🔨 chore

#15 feat: 탐색 페이지 제작
  src/components/place-item-card/PlaceItemCard.test.tsx
  src/components/place-item-card/PlaceItemCard.tsx
  src/components/share/TagButton.tsx
  src/context/categoryContext.tsx
  src/context/tagContext.tsx
  src/features/discover/apis/filterApi.ts
  src/features/discover/apis/placeApi.ts
  src/features/discover/components/CategoryFilter.tsx
  src/features/discover/components/DiscoverItem.tsx
  src/features/discover/components/TagFilter.tsx
  src/mock/handler/PlaceEndpoints.ts
  src/pages/DiscoverPage.tsx
  src/types/type.ts
Labels: 🚀 feature

#17 feat: MainPage 생성
  public/asset/header/sejongUnivImg.png
  public/asset/place-item-card/cafe-example.jpg
  public/asset/place-item-card/restaurant-example2.jpg
  src/components/place-item-container/Banner.tsx
  src/components/place-item-container/ItemContainer.tsx
  src/components/place-item-container/model/type.ts
  src/mock/handler/PlaceEndpoints.ts
  src/pages/MainPage.tsx
Labels: 🚀 feature

#16 feat: 상세 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/features/discover/apis/placeApi.ts
  src/features/placeDetail/LightboxViewer.tsx
  src/features/placeDetail/PhotoGrid.tsx
  src/features/placeDetail/PhotoStrip.tsx
  src/features/placeDetail/PlaceDetailContainer.tsx
  src/features/placeDetail/PlaceInfo.tsx
  src/index.css
  src/main.tsx
  src/mock/handler/PlaceEndpoints.ts
  src/pages/PlaceDetailPage.tsx
Labels: 🚀 feature

#24 refactor: 탐색 페이지 리팩토링
  src/App.tsx
  src/components/place-item-card/PlaceItemCard.tsx
  src/components/place-item-container/Banner.tsx
  src/components/share/TagButton.tsx
  src/context/tagContext.tsx
  src/features/explore/apis/filterApi.ts
  src/features/explore/apis/placeApi.ts
  src/features/explore/components/CategoryFilter.test.tsx
  src/features/explore/components/CategoryFilter.tsx
  src/features/explore/components/ExploreItem.tsx
  src/features/explore/components/Filter.tsx
  src/features/explore/components/TagFilter.test.tsx
  src/features/explore/components/TagFilter.tsx
  src/features/placeDetail/PlaceInfo.tsx
  src/layout/components/Header.test.tsx
  src/layout/components/Header.tsx
  src/pages/DiscoverPage.tsx
  src/pages/ExplorePage.tsx
Labels: 🧹 refactor

#26 refactor: Mainpage 개선 🥝
  jsrepo.json
  package-lock.json
  package.json
  public/asset/header/Logo.svg
  public/asset/header/loginIcon.svg
  public/asset/header/logoutIcon.svg
  public/asset/header/newLogo.svg
  public/asset/header/sejongUnivImg.png
  public/asset/itemContainer/hotPlaceIcon.svg
  public/asset/pageRouterButton/allItemIcon.svg
  public/asset/pageRouterButton/cafeIcon.svg
  public/asset/pageRouterButton/restaurantIcon.svg
  public/asset/pageRouterButton/rouletteIcon.svg
  src/App.tsx
  src/blocks/Animations/LogoLoop/LogoLoop.tsx
  src/components/place-item-container/Banner.tsx
  src/components/place-item-container/ItemContainer.tsx
  src/components/place-item-container/model/type.ts
  src/components/share/PageRouterButton.tsx
  src/components/share/TextType.tsx
  src/font/Pretendard-Black.woff2
  src/font/Pretendard-Bold.woff2
  src/font/Pretendard-ExtraBold.woff2
  src/font/Pretendard-ExtraLight.woff2
  src/font/Pretendard-Light.woff2
  src/font/Pretendard-Medium.woff2
  src/font/Pretendard-Regular.woff2
  src/font/Pretendard-SemiBold.woff2
  src/font/Pretendard-Thin.woff2
  src/index.css
  src/layout/Layout.tsx
  src/layout/components/Footer.tsx
  src/layout/components/Header.tsx
  src/mock/handler/PlaceEndpoints.ts
  src/pages/MainPage.tsx
  src/pages/PrepareServicePage.tsx
  tailwind.config.js
Labels: 🚀 feature, 🧹 refactor

#29 feat: 리뷰 페이지 구현
  src/App.tsx
  src/api/placeApi.ts
  src/api/tagApi.ts
  src/components/share/TagButton.tsx
  src/features/createReview/api/postReviewApi.ts
  src/features/createReview/components/CreateReview.tsx
  src/features/createReview/components/StarRating.tsx
  src/mock/handler/PlaceEndpoints.ts
  src/pages/CreateReviewPage.tsx
  src/types/type.ts
Labels: 🚀 feature

#31 refactor: 각 컴포넌트 디자인 개선
  public/asset/place-item-card/cafe-example.jpg
  public/asset/place-item-card/restaurant-example2.jpg
  src/components/place-item-card/PlaceItemCard.tsx
  src/components/share/TagButton.tsx
Labels: 🧹 refactor

#33 feat: 로그인 ui 추가
  src/features/login/components/LoginForm.tsx
  src/features/login/components/LoginModal.tsx
  src/layout/Layout.tsx
  src/layout/components/Header.tsx
Labels: 🚀 feature
